#!/bin/bash

set -eu

# Disable getty on tty1
ln -sf "/dev/null" "$1/etc/systemd/system/getty@tty1.service"

# configure the splash screen
mkdir -p $1/usr/share/plymouth/themes/kaptive
chmod 755 $1/usr/share/plymouth/themes/kaptive

rsync -a ../plymouth/themes/kaptive $1/usr/share/plymouth/themes/

chmod 644 $1/usr/share/plymouth/themes/kaptive/*

# set the default theme to kaptive
chroot $1 plymouth-set-default-theme kaptive
